flaskapp/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import TextAreaField
from wtforms.validators import DataRequired
from wtforms.validators import Email
from wtforms.validators import Length


class ContactUs(FlaskForm):
    name = StringField("Name",
                       validators=[DataRequired(),
                                   Length(min=2, max=20)])
    email = StringField("Email", validators=[DataRequired(), Email()])
    mobile = StringField("Mobile", validators=[Length(4, 16)])
    subject = StringField("Subject",
                          validators=[DataRequired(),
                                      Length(5, 200)])
    message = TextAreaField("Message",
                            validators=[DataRequired(),
                                        Length(5, 10000)])

flaskapp/__init__.py
import os

from flask import Flask
from flask_bcrypt import Bcrypt
from flask_caching import Cache
from flask_login import LoginManager
from flask_mail import Mail
from flask_minify import minify
from flask_sqlalchemy import SQLAlchemy

from flaskapp.config import Config

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = "users.login"
login_manager.login_message_category = "info"
mail = Mail()
cache = Cache()
APP_PATH = os.path.dirname(os.path.abspath(__file__))
TEST_DB = "test.db"


def create_app(config_class=Config):
    """To create

    Keyword Arguments:
        config_class {object} -- It configures app (default: {Config})

    Returns:
        App -- it creates app using configuration from config_class
    """
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    cache.init_app(app)
    minify(app=app, html=True, js=True, cssless=True)

    from flaskapp.blueprints.users.routes import users
    from flaskapp.blueprints.courses.routes import courses
    from flaskapp.blueprints.questions.routes import questions
    from flaskapp.blueprints.main.routes import main
    from flaskapp.blueprints.errors.routes import errors
    from flaskapp.blueprints.papers.routes import papers

    app.register_blueprint(users)
    app.register_blueprint(courses)
    app.register_blueprint(questions)
    app.register_blueprint(main)
    app.register_blueprint(errors)
    app.register_blueprint(papers)

    return app

flaskapp/blueprints/__init__.py
"""blueprints for the application"""

flaskapp/blueprints/courses/__init__.py
"""course blueprint"""

flaskapp/blueprints/courses/routes.py
from flask import Blueprint
from flask import flash
from flask import render_template
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from werkzeug.utils import redirect

from flaskapp import db
from flaskapp.blueprints.courses.forms import CourseForm
from flaskapp.blueprints.courses.forms import UnitForm
from flaskapp.checkers import check_valid_course
from flaskapp.models import Course
from flaskapp.models import Unit
from flaskapp.utils import profile_path

courses = Blueprint("courses", __name__)


@courses.route("/course/new/", methods=["GET", "POST"])
@login_required
def add_course():
    """Rendering to add course page

    Returns:
        HTML function -- For adding new course to user's account. After submitting new course redirect to courses page.Else show form which
        shows add course feild.
    """
    form = CourseForm()
    if form.validate_on_submit():
        _course = Course(name=form.course.data, teacher=current_user)
        db.session.add(_course)
        db.session.commit()
        flash("New course added successfully!", "success")
        return redirect(url_for("courses.all_courses"))
    return render_template(
        "course/course_form.html",
        form=form,
        css_files=["css/base.css", "css/course/courses_form.css"],
        js_files=["js/course/add_course.js"],
        image_file=profile_path(),
        title="Add Courses",
    )


@courses.route("/course/")
@login_required
def all_courses():
    """Show listed down course of user

    Returns:
        HTML function -- Redirect to courses pages where listed down all courses.
    """
    _courses = Course.query.filter(Course.teacher == current_user).all()
    return render_template(
        "course/courses.html",
        courses=_courses,
        css_files=["css/base.css", "css/course/courses.css"],
        js_files=["js/course/remove_course.js"],
        image_file=profile_path(),
        title="Courses",
    )


@courses.route("/course/delete/", methods=["GET", "POST"])
@login_required
def delete_course():
    """Delete course from list of courses
    """
    if request.method == "POST":
        course_ids = request.get_json()
        db.session.query(Course).filter(
            Course.id.in_(course_ids)).delete(synchronize_session="fetch")
        db.session.commit()
    return redirect(url_for("courses.all_courses"))


@courses.route("/course/<course_id>/unit/")
@login_required
@check_valid_course
def all_units(course_id):
    """Give all units list of course with given course ID

    Args:
        course_id (int): Course ID of Course

    Returns:
        HTML: returns question page for course
    """
    _course = Course.query.filter(Course.id == course_id).first()
    _units = Unit.query.filter(Unit.course == _course).all()
    return render_template(
        "course/units.html",
        course_id=course_id,
        image_file=profile_path(),
        units=_units,
        title="Units",
        css_files=["css/base.css", "css/course/courses.css"],
        js_files=["js/course/remove_course.js"],
    )


@courses.route("/course/<course_id>/unit/new", methods=["GET", "POST"])
@login_required
@check_valid_course
def add_unit(course_id):
    """Add unit to course

    Args:
        course_id (int): ID of course

    Returns:
        HTML: Go to question of units template
    """
    _course = Course.query.filter(Course.id == course_id).first()
    form = UnitForm(_course)
    if form.validate_on_submit():
        unit = Unit(chapter_no=form.chapter_no.data,
                    name=form.name.data,
                    course=_course)
        db.session.add(unit)
        db.session.commit()
        flash("New unit added successfully!", "success")
        return redirect(url_for("courses.all_units", course_id=course_id))
    return render_template(
        "course/unit_form.html",
        course_id=course_id,
        form=form,
        css_files=["css/base.css", "css/course/courses_form.css"],
        js_files=["js/course/add_unit.js"],
        image_file=profile_path(),
        title="Add Units",
    )


@courses.route("/course/<course_id>/unit/delete/", methods=["GET", "POST"])
@login_required
@check_valid_course
def delete_unit(course_id):
    """Delete unit for given course

    Args:
        course_id (int): Course id which user want to delete
    """
    if request.method == "POST":
        unit_ids = request.get_json()
        db.session.query(Unit).filter(
            Unit.id.in_(unit_ids)).delete(synchronize_session="fetch")
        db.session.commit()
    return redirect(url_for("courses.all_units", course_id=course_id))

flaskapp/blueprints/main/__init__.py
"""main blueprint"""

flaskapp/blueprints/papers/__init__.py
"""papers blueprint"""

flaskapp/blueprints/papers/routes.py
import itertools
from collections import Counter
from collections import defaultdict
from string import ascii_lowercase

from flask import Blueprint
from flask import flash
from flask import jsonify
from flask import redirect
from flask import render_template
from flask import request
from flask import session
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from flask_weasyprint import render_pdf
from qpt_generator import QPTGenerator

from flaskapp import db
from flaskapp.blueprints.papers.forms import ExaminerEmailForm
from flaskapp.blueprints.papers.forms import MarkDistributionForm
from flaskapp.blueprints.papers.forms import PaperLogoForm
from flaskapp.blueprints.papers.utils import email_pdf
from flaskapp.blueprints.papers.utils import find_conflicting_questions
from flaskapp.blueprints.papers.utils import find_random_question
from flaskapp.blueprints.papers.utils import QuestionNotFoundError
from flaskapp.blueprints.papers.utils import render_paper
from flaskapp.blueprints.papers.utils import save_logo
from flaskapp.checkers import check_valid_course
from flaskapp.checkers import check_valid_paper
from flaskapp.checkers import check_valid_session
from flaskapp.models import Course
from flaskapp.models import Paper
from flaskapp.models import Question
from flaskapp.utils import CognitiveEnum
from flaskapp.utils import DifficultyEnum
from flaskapp.utils import json_url
from flaskapp.utils import profile_path
from flaskapp.utils import QuestionTypeEnum

papers = Blueprint("papers", __name__)


@papers.route("/home")
@login_required
def home():
    """Render Home page
    Returns:
        HTML -- It will render home page.
    """
    main_page = request.args.get("page", 1, type=int)
    _courses = Course.query.filter(Course.teacher == current_user).all()
    course_ids = [course.id for course in _courses]
    _papers = Paper.query.filter(Paper.course_id.in_(course_ids)).paginate(
        page=main_page, per_page=10)
    return render_template(
        "papers/home.html",
        css_files=["css/base.css", "css/papers/home.css"],
        papers=_papers,
        title="Home",
        image_file=profile_path(),
    )


@papers.route("/course/<course_id>/papers/generate/request",
              methods=["GET", "POST"])
@login_required
@check_valid_course
def paper_generate_request(course_id):
    """ generate paper from json data
    """
    if request.method == "POST":
        data = request.get_json()
        if data:
            session["total_marks"] = json_url.dumps(data["total_marks"])
            session["no_of_subquestions"] = json_url.dumps(data["questions"])
            return redirect(
                url_for(
                    "papers.mark_distribution_form",
                    course_id=course_id,
                ))
        flash("Form can't be empty!")
    return render_template(
        "papers/generate_request.html",
        js_files=["js/papers/generate_request.js"],
        css_files=["css/papers/generate_request.css", "css/base.css"],
        image_file=profile_path(),
    )


@papers.route("/course/<course_id>/papers/generate/form/",
              methods=["GET", "POST"])
@login_required
@check_valid_course
@check_valid_session(session_keys=("total_marks", "no_of_subquestions"))
def mark_distribution_form(course_id):
    """Mark distribution of form
    Args:
        course_id (int): Course ID of course
    Returns:
        HTML: Go to mark distribution form page
    """
    total_marks = json_url.loads(session["total_marks"])
    no_of_subquestions = json_url.loads(session["no_of_subquestions"])
    form = MarkDistributionForm(course_id, no_of_subquestions, total_marks)
    if form.validate_on_submit():
        question_no = list(
            itertools.chain(*map(
                lambda x: list(itertools.repeat(x[0] + 1, x[1])),
                enumerate(no_of_subquestions),
            )))
        raw_template = QPTGenerator(dict(form.data), question_no).generate()
        paper_template = defaultdict(lambda: defaultdict(dict))
        subque_counter = Counter()
        que_counter = defaultdict(dict)
        for i in range(len(raw_template["question_no"])):
            data = dict(
                mark=raw_template["question"][i],
                cognitive=CognitiveEnum(raw_template["cognitive"][i]).name,
                difficulty=DifficultyEnum(raw_template["difficulty"][i]).name,
                unit=raw_template["unit"][i],
            )
            question_type = QuestionTypeEnum(
                raw_template["question_type"][i]).name
            if raw_template["question_no"][i] not in que_counter[
                    question_type]:
                que_counter[question_type][raw_template["question_no"][i]] = (
                    len(que_counter[question_type]) + 1)
            current_que = que_counter[question_type][
                raw_template["question_no"][i]]
            current_subque = ascii_lowercase[subque_counter[(question_type,
                                                             current_que)]]
            paper_template[question_type][current_que][current_subque] = data
            subque_counter[(question_type, current_que)] += 1
        session["paper_template"] = json_url.dumps(dict(paper_template))
        return redirect(
            url_for("papers.confirm_paper_template", course_id=course_id))
    return render_template("papers/mark_distribution_form.html",
                           form=form,
                           title="Mark Distribution")


@papers.route("/course/<course_id>/papers/confirm/template/",
              methods=["GET", "POST"])
@login_required
@check_valid_course
@check_valid_session(session_keys=("paper_template", ))
def confirm_paper_template(course_id):
    if request.method == "POST":
        if request.get_json():
            return redirect(
                url_for("papers.generate_paper", course_id=course_id))
        flash("Form can't be empty!")
    paper_template = json_url.loads(session["paper_template"])
    return render_template(
        "papers/confirm_paper_template.html",
        course_id=course_id,
        paper_template=paper_template,
        css_files=["css/papers/confirm_paper_template.css"],
        js_files=["js/papers/confirm_paper_template.js"],
        image_file=profile_path(),
        title="Mark Distribution",
    )


@papers.route("/course/<course_id>/papers/generate/", methods=["GET", "POST"])
@login_required
@check_valid_course
@check_valid_session(session_keys=("paper_template", "total_marks"))
def generate_paper(course_id):
    paper_template = json_url.loads(session["paper_template"])
    conflicting_questions = []
    for qtype in paper_template:
        for question in paper_template[qtype]:
            for subquestion, constraints in paper_template[qtype][
                    question].items():
                constraints["cognitive"] = CognitiveEnum.from_string(
                    constraints["cognitive"])
                constraints["difficulty"] = DifficultyEnum.from_string(
                    constraints["difficulty"])
                constraints["question_type"] = QuestionTypeEnum.from_string(
                    qtype)
                conflicting_questions.extend(
                    find_conflicting_questions(course_id, constraints))
                paper_template[qtype][question][subquestion] = constraints
    form = PaperLogoForm()
    if form.validate_on_submit():
        paper_data = {}
        if form.picture.data:
            paper_data["paper_logo"] = save_logo(form.picture.data)
        paper_data["name"] = form.name.data
        paper_data["term"] = form.term.data
        paper_data["mark"] = json_url.loads(session["total_marks"])
        paper_data["exam_date"] = form.exam_date.data
        paper_data["time_limit"] = form.time_limit.data
        paper_data["course_id"] = course_id
        paper_data["paper_format"] = defaultdict(lambda: defaultdict(dict))
        for qtype in paper_template:
            for question in paper_template[qtype]:
                for subquestion, constraints in paper_template[qtype][
                        question].items():
                    try:
                        paper_data["paper_format"][qtype][question].update({
                            subquestion:
                            find_random_question(course_id, constraints)
                        })

                    except QuestionNotFoundError:
                        flash(
                            "Question that satisfies all given constraints doesn't exist in database."
                        )
                        return redirect(url_for("papers.home"))
        paper_data["paper_format"] = dict(paper_data["paper_format"])
        paper = Paper(**paper_data)
        db.session.add(paper)
        db.session.commit()
        return redirect(
            url_for("papers.confirm_generated_paper", paper_id=paper.id))
    return render_template(
        "papers/generate_paper.html",
        conflicting_questions=conflicting_questions,
        course_id=course_id,
        form=form,
    )


@papers.route("/papers/handle/conflicts", methods=["GET", "POST"])
@login_required
def handle_conflicting_questions():
    # data = {"mcq":{"ask": [], "nask": []}, "sub": {"ask": [], "nask": []}}
    if request.method == "POST":
        data = request.get_json()
        for qtype in data:
            db.session.query(Question).filter(
                Question.id.in_(data[qtype].get("nask", []))).update(
                    dict(imp=False), synchronize_session="fetch")
            db.session.query(Question).filter(
                Question.id.in_(data[qtype].get("ask", []))).update(
                    dict(is_asked=False), synchronize_session="fetch")
            db.session.commit()
        return jsonify(dict(status="OK"))


@papers.route("/papers/<paper_id>")
@login_required
@check_valid_paper
def pdf_paper(paper_id):

flaskapp/blueprints/questions/__init__.py
"""questions blueprint"""

flaskapp/blueprints/users/__init__.py
"""users blueprint"""

flaskapp/templates/papers/confirm_generated_paper.html
{% extends "base.html" %}

{% block special_top_links %}
    <a class="top_navigation_items" href={{ url_for("courses.all_courses") }}>
        <h4 class="py-2 mx-3">Courses</h4>
    </a>
{% endblock special_top_links %}

{% block special_side_links %}
    <a class="side_navigation_items" href={{ url_for("courses.all_courses") }}>Courses</a>
{% endblock special_side_links %}

{% block main %}

<object data='{{url_for("papers.pdf_paper", paper_id=paper_id)}}' type="application/pdf" id="embed_pdf">
    Browser does not support embedding of pdf
</object>
<div style="font-size: 20px"><a href='{{url_for("papers.pdf_paper", paper_id=paper_id)}}' target="_blank">Click Here</a> to view Demo</div>
<br /><br />
<div style="font-size: 20px">Mail paper to examiner</div>
<form method="post" novalidate id="generate_pdf">
    {{form.hidden_tag() }}
    <div id="form_content">
        <div class="form__fields">
            {{form.examiner_email.label()}}
            {{form.examiner_email(class='email_form')}}
            <div class="form_client_error"></div>
            {% if form.examiner_email.errors %}
            <ul class="form__error">
                {% for error in form.examiner_email.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
        <div class="btn_container" style="margin-right: 0">
            <button type="submit" id="abort">Abort</button>
            <button type="submit" id="pdf_mail">Submit</button>
        </div>
    </div>
</form>
{% endblock main %}

flaskapp/templates/papers/confirm_paper_template.html
{% extends "base.html" %}

{% block special_top_links %}
    <a class="top_navigation_items" href={{ url_for("courses.all_courses") }}>
        <h4 class="py-2 mx-3">Courses</h4>
    </a>
{% endblock special_top_links %}

{% block special_side_links %}
    <a class="side_navigation_items" href={{ url_for("courses.all_courses") }}>Courses</a>
{% endblock special_side_links %}

{% block flashes %}
{% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %}
<ul class="flashes flashes_question">
    {% for category, message in messages %}
    <li class="{{ category }}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %} {% endwith %}
{% endblock flashes %}

{% block header %}
  <h3>Mark Distribution</h3>
{% endblock header %}

{% block main %}

<div id="mark_distribution_container">
    <div id="subjective_part">
        <div id="subjective_part_title">Subjective Question</div>
        <div id="subjective_mark_distribution"></div>
    </div>
    <div id="mcq_part">
        <div id="mcq_part_title">MCQs</div>
        <div id="mcq_mark_distribution"></div>
    </div>
</div>
<a href='{{url_for("papers.paper_generate_request", course_id=course_id)}}' id="go_back">
    Try Again
</a>
<button id="generate_paper" data-id="{{course_id}}">
    Generate Paper
</button>
<script type="text/javascript" id="trial">
    const markDistribution = {{ paper_template|tojson|safe }}
</script>
{% endblock main %}

flaskapp/templates/papers/generate_paper.html
{% extends "base.html" %}

{%block main %}
<hr id="start"/>
<div id="conflicts_container">
    {% for q in conflicting_questions %}
    {% if loop.index==1%}
    <div id="conflicts_message">These questions are previously asked. Select questions to include in current paper</div>
    {% endif %}
    <div class="question_info">
                <div class="first_row">
                    <div class="first_row_column_1" data-id="{{ q.id }}"></div>
                    <div class="first_row_column_2">
                        {{ q.imp }}</div>
                    <div class="first_row_column_3">
                        {{q.question_type}}
                    </div>
                </div>
                <div class="second_row">
                    <div><span class="left">Marks</span>:
                        <span class="marks">{{ q.mark }}</span></div>
                </div>
                <div class="third_row">
                    <div><span class="left">Difficulty</span>:
                        <span class="difficulty">{{ q.difficulty }}</span></div>
                </div>
                <div class="fourth_row">
                    <div><span class="left">Cognitive
                            level</span>: <span class="cognitive"> {{
                            q.cognitive_level }}</span></div>
                </div>
                <div class="fifth_row">
                        <span class="left">Unit</span>:
                        <span class="cognitive">
                            {{ q.unit_id }}
                        </span>
                </div>
                <div class="sixth_row">
                        <span class="left">Question</span>: <div class="question_description">
                            {{ q.question.question }}
                        </div>
                </div>
                {%if q.question_type=='mcq' %}
                <div class="options_container">
                            <div class="options_final_value">{{ q.question.option1 }}</div>
                            <div class="options_final_value">{{ q.question.option2 }}</div>
                            <div class="options_final_value">{{ q.question.option3 }}</div>
                            <div class="options_final_value">{{ q.question.option4 }}</div>
                </div>
                {% endif %}
                <div class="include">
                <label for="checkbox_label_{{loop.index}}" class="label_checkbox">Add into Paper</label>
                    <input type="checkbox" class="add_checkbox" id="checkbox_label_{{loop.index}}"/>
                <div class="toggle_container">
                    <div class="toggle_btn"></div>
                </div>
                include in Papers
                </div>
                {% if loop.index==loop.length %}
                <div class="btn_container">
                    <button id="fix_conflicts">Fix Conflicts</button>
                </div>
                {% endif %}
            </div>
    {% endfor %}
</div>

<div id="paper_logo">
    <form id="logoform" method="post" action='{{url_for("papers.generate_paper", course_id=course_id)}}' novalidate enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div id="form_content">
            <div class="form__fields">
                {{ form.name.label() }}
                {{ form.name(class='paper_fields') }}
                <div class="form_client_error"></div>
                {% if form and form.name.errors %}
                    <ul class="form__error">
                        {% for error in form.name.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
            </div>
            <div class="form__fields">
                {{ form.term.label() }}
                {{ form.term(class='paper_fields') }}
                <div class="form_client_error"></div>
                {% if form and form.term.errors %}
                    <ul class="form__error">
                        {% for error in form.term.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
            </div>
            <div class="form__fields">
                {{ form.exam_date.label() }}
                {{ form.exam_date(class='paper_fields') }}
                <div class="form_client_error"></div>
                {% if form and form.exam_date.errors %}
                    <ul class="form__error">
                        {% for error in form.exam_date.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
            </div>
            <div class="form__fields">
                {{ form.time_limit.label() }}
                {{ form.time_limit(class='paper_fields') }}
                <div class="form_client_error"></div>
                {% if form and form.time_limit.errors %}
                    <ul class="form__error">
                        {% for error in form.time_limit.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
            </div>
            <div class="form__fields">
                {{ form.picture.label() }}
                {{ form.picture(class='paper_fields') }}
                <div class="form_client_error"></div>
                {% if form and form.picture.errors %}
                    <ul class="form__error">
                        {% for error in form.picture.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
            </div>
            <div class="btn_container">
                {{ form.submit(id="generate_paper") }}
            </div>
        </div>
    </form>
</div>
<hr id="end"/>
{%endblock main %}

flaskapp/templates/papers/home.html
{% extends "base.html" %}

{% block header %}
<h1 class="header">Recent</h1>
{% endblock header %}

{% block special_side_links %}
  <a class="side_navigation_items" href={{ url_for("courses.all_courses") }} >Courses</a>
{% endblock special_side_links %}

{% block flashes %}
{% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %}
<ul class="flashes flashes_question">
    {% for category, message in messages %}
    <li class="{{ category }}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %} {% endwith %}
{% endblock flashes %}

{% block main %}
   {% if papers %}
<div id="paper_container">
   {% for paper in papers.items %}
   <div class="papers">
       <div class="paper_fields">
           Paper : {{paper.name}}
       </div>
       <div class="paper_fields">
           Exam Date : {{paper.exam_date}}
       </div>
       <div class="paper_fields">
           Term : {{paper.term}}
       </div>
       <div class="paper_fields">
           Marks : {{paper.mark}}
       </div>
       <div class="links"><a href='{{url_for("papers.pdf_paper",paper_id = paper.id)}}' target="_blank">View Paper</a></div>
   </div>
   {% endfor %}
</div>
<div id="pagination">
   {% for page_num in papers.iter_pages(left_edge=1,
                                                right_edge=1,
                                                left_current=1,
                                                right_current=2) %}
   {% if page_num %}
    {% if papers.page == page_num %}
    <a class="btn btn-info mb-4"
        href="{{ url_for('papers.home',page=page_num) }}">{{ page_num }}</a>
    {% else %}
    <a class="btn btn-outline-info mb-4"
        href="{{ url_for('papers.home',page=page_num) }}">{{ page_num }}</a>
    {% endif %}
    {% else %}
    ...
    {% endif %}
   {% endfor %}
</div>
   {% endif %}
{% endblock main %}

{% block sideNav %}
<div class="ml-4" id="home_nav">
    <a class="row pl-2" id="manage_courses_btn" href={{ url_for("courses.all_courses") }}>
        <h1 class="px-3 py-1">C</h1>
        <div class="col">
            <h3>Manage</h3>
            <h5>Courses</h5>
        </div>
    </a>
</div>
{% endblock sideNav %}

flaskapp/templates/papers/papers.html
{% extends "base.html" %}

{% block special_top_links %}
    <a class="top_navigation_items" href={{ url_for("courses.all_courses") }}>
        <h4 class="py-2 mx-3">Courses</h4>
    </a>
{% endblock special_top_links %}

{% block special_side_links %}
    <a class="side_navigation_items" href={{ url_for("courses.all_courses") }}>Courses</a>
{% endblock special_side_links %}

{% block main %}
   {% if papers %}
<div id="paper_container">
   {% for paper in papers.items %}
   <div class="papers">
       <div class="paper_fields">
           Paper : {{paper.name}}
       </div>
       <div class="paper_fields">
           Exam Date : {{paper.exam_date}}
       </div>
       <div class="paper_fields">
           Term : {{paper.term}}
       </div>
       <div class="paper_fields">
           Marks : {{paper.mark}}
       </div>
       <div class="links"><a href='{{url_for("papers.pdf_paper",paper_id = paper.id)}}' target="_blank">View Paper</a></div>
   </div>
   {% endfor %}
</div>
<div id="pagination">
   {% for page_num in papers.iter_pages(left_edge=1,
                                                right_edge=1,
                                                left_current=1,
                                                right_current=2) %}
   {% if page_num %}
    {% if papers.page == page_num %}
    <a class="btn btn-info mb-4"
        href="{{ url_for('papers.all_papers', page=page_num, course_id=papers.items[0].course_id) }}">{{ page_num }}</a>
    {% else %}
    <a class="btn btn-outline-info mb-4"
        href="{{ url_for('papers.all_papers', page=page_num, course_id=papers.items[0].course_id) }}">{{ page_num }}</a>
    {% endif %}
    {% else %}
    ...
    {% endif %}
   {% endfor %}
</div>
   {% endif %}
{% endblock main %}