flaskapp/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import TextAreaField
from wtforms.validators import DataRequired
from wtforms.validators import Email
from wtforms.validators import Length


class ContactUs(FlaskForm):
    name = StringField("Name",
                       validators=[DataRequired(),
                                   Length(min=2, max=20)])
    email = StringField("Email", validators=[DataRequired(), Email()])
    mobile = StringField("Mobile", validators=[Length(4, 16)])
    subject = StringField("Subject",
                          validators=[DataRequired(),
                                      Length(5, 200)])
    message = TextAreaField("Message",
                            validators=[DataRequired(),
                                        Length(5, 10000)])

flaskapp/__init__.py
import os

from flask import Flask
from flask_bcrypt import Bcrypt
from flask_caching import Cache
from flask_login import LoginManager
from flask_mail import Mail
from flask_minify import minify
from flask_sqlalchemy import SQLAlchemy

from flaskapp.config import Config

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = "users.login"
login_manager.login_message_category = "info"
mail = Mail()
cache = Cache()
APP_PATH = os.path.dirname(os.path.abspath(__file__))
TEST_DB = "test.db"


def create_app(config_class=Config):
    """To create

    Keyword Arguments:
        config_class {object} -- It configures app (default: {Config})

    Returns:
        App -- it creates app using configuration from config_class
    """
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    cache.init_app(app)
    minify(app=app, html=True, js=True, cssless=True)

    from flaskapp.blueprints.users.routes import users
    from flaskapp.blueprints.courses.routes import courses
    from flaskapp.blueprints.questions.routes import questions
    from flaskapp.blueprints.main.routes import main
    from flaskapp.blueprints.errors.routes import errors
    from flaskapp.blueprints.papers.routes import papers

    app.register_blueprint(users)
    app.register_blueprint(courses)
    app.register_blueprint(questions)
    app.register_blueprint(main)
    app.register_blueprint(errors)
    app.register_blueprint(papers)

    return app

flaskapp/blueprints/__init__.py
"""blueprints for the application"""

flaskapp/blueprints/courses/__init__.py
"""course blueprint"""

flaskapp/blueprints/courses/routes.py
from flask import Blueprint
from flask import flash
from flask import render_template
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from werkzeug.utils import redirect

from flaskapp import db
from flaskapp.blueprints.courses.forms import CourseForm
from flaskapp.blueprints.courses.forms import UnitForm
from flaskapp.checkers import check_valid_course
from flaskapp.models import Course
from flaskapp.models import Unit
from flaskapp.utils import profile_path

courses = Blueprint("courses", __name__)


@courses.route("/course/new/", methods=["GET", "POST"])
@login_required
def add_course():
    """Rendering to add course page

    Returns:
        HTML function -- For adding new course to user's account. After submitting new course redirect to courses page.Else show form which
        shows add course feild.
    """
    form = CourseForm()
    if form.validate_on_submit():
        _course = Course(name=form.course.data, teacher=current_user)
        db.session.add(_course)
        db.session.commit()
        flash("New course added successfully!", "success")
        return redirect(url_for("courses.all_courses"))
    return render_template(
        "course/course_form.html",
        form=form,
        css_files=["css/base.css", "css/course/courses_form.css"],
        js_files=["js/course/add_course.js"],
        image_file=profile_path(),
        title="Add Courses",
    )


@courses.route("/course/")
@login_required
def all_courses():
    """Show listed down course of user

    Returns:
        HTML function -- Redirect to courses pages where listed down all courses.
    """
    _courses = Course.query.filter(Course.teacher == current_user).all()
    return render_template(
        "course/courses.html",
        courses=_courses,
        css_files=["css/base.css", "css/course/courses.css"],
        js_files=["js/course/remove_course.js"],
        image_file=profile_path(),
        title="Courses",
    )


@courses.route("/course/delete/", methods=["GET", "POST"])
@login_required
def delete_course():
    """Delete course from list of courses
    """
    if request.method == "POST":
        course_ids = request.get_json()
        db.session.query(Course).filter(
            Course.id.in_(course_ids)).delete(synchronize_session="fetch")
        db.session.commit()
    return redirect(url_for("courses.all_courses"))


@courses.route("/course/<course_id>/unit/")
@login_required
@check_valid_course
def all_units(course_id):
    """Give all units list of course with given course ID

    Args:
        course_id (int): Course ID of Course

    Returns:
        HTML: returns question page for course
    """
    _course = Course.query.filter(Course.id == course_id).first()
    _units = Unit.query.filter(Unit.course == _course).all()
    return render_template(
        "course/units.html",
        course_id=course_id,
        image_file=profile_path(),
        units=_units,
        title="Units",
        css_files=["css/base.css", "css/course/courses.css"],
        js_files=["js/course/remove_course.js"],
    )


@courses.route("/course/<course_id>/unit/new", methods=["GET", "POST"])
@login_required
@check_valid_course
def add_unit(course_id):
    """Add unit to course

    Args:
        course_id (int): ID of course

    Returns:
        HTML: Go to question of units template
    """
    _course = Course.query.filter(Course.id == course_id).first()
    form = UnitForm(_course)
    if form.validate_on_submit():
        unit = Unit(chapter_no=form.chapter_no.data,
                    name=form.name.data,
                    course=_course)
        db.session.add(unit)
        db.session.commit()
        flash("New unit added successfully!", "success")
        return redirect(url_for("courses.all_units", course_id=course_id))
    return render_template(
        "course/unit_form.html",
        course_id=course_id,
        form=form,
        css_files=["css/base.css", "css/course/courses_form.css"],
        js_files=["js/course/add_unit.js"],
        image_file=profile_path(),
        title="Add Units",
    )


@courses.route("/course/<course_id>/unit/delete/", methods=["GET", "POST"])
@login_required
@check_valid_course
def delete_unit(course_id):
    """Delete unit for given course

    Args:
        course_id (int): Course id which user want to delete
    """
    if request.method == "POST":
        unit_ids = request.get_json()
        db.session.query(Unit).filter(
            Unit.id.in_(unit_ids)).delete(synchronize_session="fetch")
        db.session.commit()
    return redirect(url_for("courses.all_units", course_id=course_id))

flaskapp/blueprints/main/__init__.py
"""main blueprint"""

flaskapp/blueprints/main/routes.py
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import url_for
from flask_login import current_user

from flaskapp.blueprints.main.forms import ContactUs
from flaskapp.blueprints.main.utils import send_contact_us_email
from flaskapp.blueprints.main.utils import send_contact_us_receipt_email
from flaskapp.utils import profile_path

main = Blueprint("main", __name__)


@main.route("/")
def index():
    """Render Home page
    Returns:
        HTML-- If the current user is authenticated then render to home page of site.
    """
    if current_user.is_authenticated:
        return redirect(url_for("papers.home"))
    return render_template(
        "main/index.html",
        title="Index",
        css_files=["css/main/index.css"],
        js_files=["js/main/index.js"],
    )


@main.route("/about-us")
def about_us():
    """Render about us page
    Returns:
        HTML  -- It will redirect to about us page.
    """

    return render_template(
        "main/about.html",
        title="About Us",
        css_files=["css/main/about.css"],
        image_file=profile_path(),
    )


@main.route("/privacy-policy")
def policy_page():
    """Go to privacy policy page

    Returns:
        HTML: render to privacy and policy page
    """
    return render_template(
        "main/privacy-policy.html",
        title="Privacy Policy",
        css_files=["css/main/privacy_policy.css"],
        image_file=profile_path(),
    )


@main.route("/terms-of-service")
def terms_of_service_page():
    """Go to terms and service page

    Returns:
        HTML: Render to terms and service page
    """
    return render_template(
        "main/terms-of-service.html",
        title="Terms Of Service",
        css_files=["css/main/terms_of_service.css"],
        image_file=profile_path(),
    )


@main.route("/help")
def help_page():
    """Render help page
    Returns:
        HTML - It will redirect to help page.
    """
    return render_template(
        "main/help.html",
        title="Help",
        css_files=["css/main/help.css"],
        image_file=profile_path(),
    )


@main.route("/contact-us", methods=["GET", "POST"])
def contact_us():
    """Render Contact us page
    Returns:
        HTML-- To collect Info from user for suggestion or bug or any comment about web-app.
    """
    form = ContactUs()
    if form.validate_on_submit():
        data = dict(
            name=form.name.data,
            email=form.email.data,
            mobile=form.mobile.data,
            subject=form.subject.data,
            message=form.message.data,
        )
        send_contact_us_email(**data)
        send_contact_us_receipt_email(**data)
        flash(
            "Your Message has recorded successfully! We will reach out soon.",
            "success")
        return redirect(url_for("main.contact_us"))
    return render_template(
        "main/contact-us/contact_us_form.html",
        title="Contact Us",
        form=form,
        css_files=["css/contact_us/main.css", "css/contact_us/util.css"],
        image_file=profile_path(),
    )

flaskapp/blueprints/papers/__init__.py
"""papers blueprint"""

flaskapp/blueprints/questions/__init__.py
"""questions blueprint"""

flaskapp/blueprints/users/__init__.py
"""users blueprint"""

flaskapp/blueprints/users/routes.py
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from flask_login import login_user
from flask_login import logout_user

from flaskapp import bcrypt
from flaskapp import db
from flaskapp.blueprints.users.forms import LoginForm
from flaskapp.blueprints.users.forms import RegistrationForm
from flaskapp.blueprints.users.forms import RequestResetForm
from flaskapp.blueprints.users.forms import ResetPasswordForm
from flaskapp.blueprints.users.forms import UpdateAccountForm
from flaskapp.blueprints.users.utils import save_picture
from flaskapp.blueprints.users.utils import send_reset_email
from flaskapp.models import User
from flaskapp.utils import profile_path

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    """Registeration of user

    Returns:
        HTML function/ page -- If user is authenticated then redirect to papers.home page.
        after submitting the form for registration go to login page.
        and when this page is load returns HTML function.
    """
    if current_user.is_authenticated:
        return redirect(url_for("papers.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode("utf-8")
        user = User(username=form.username.data,
                    email=form.email.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created! You are now able to log in",
              "success")
        return redirect(url_for("users.login"))
    return render_template(
        "users/register.html",
        title="Register",
        form=form,
        css_files=["css/users/register.css"],
        js_files=["js/users/register.js"],
        btn_name="Back",
    )


@users.route("/login", methods=["GET", "POST"])
def login():
    """Login into system

    Returns:
        HTML function/page -- If the user is authenticated then redirect to papers home page
        else after logging in(with validation of correct details) go to papers home page
        and while runnig this page gives tempalte of login.htm.
    """
    if current_user.is_authenticated:
        return redirect(url_for("papers.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            return (redirect(next_page) if next_page else redirect(
                url_for("papers.home")))
        flash("Login Unsuccessful. Please check email and password", "danger")
    return render_template(
        "users/login.html",
        title="Login",
        form=form,
        css_files=["css/users/login.css"],
        js_files=["js/users/login.js"],
        btn_name="Back",
    )


@users.route("/logout")
@login_required
def logout():
    """For Logout

    Returns:
        Page -- It will redirect to mail index page
    """
    logout_user()
    return redirect(url_for("main.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    """Accout of User

    Returns:
        Rendering page -- If user want to change profile pic or name or email.
        it will do it.
    """
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for("users.account"))
    form.username.data = current_user.username
    form.email.data = current_user.email
    image_file = profile_path()
    return render_template(
        "users/account.html",
        title="Account",
        css_files=["css/base.css", "css/users/accounts.css"],
        image_file=image_file,
        form=form,
        js_files=["js/users/account.js"],
    )


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    """For reset password

    Returns:
        Page -- If user want to reset password it will allow it by email verification.Mail will
        sent to user's mail and page will render to home login page.
    """
    if current_user.is_authenticated:
        return redirect(url_for("papers.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash(
            "An email has been sent with instructions to reset your password.",
            "info")
        return redirect(url_for("users.login"))
    return render_template(
        "users/reset_request.html",
        title="Reset Password",
        form=form,
        js_files=["js/users/reset_password.js"],
    )


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    """reset password's token

    Arguments:
        token {Token} -- Object

    Returns:
        page -- If user is authenticated then redirect to home page.
        If user is none then shows warning.else show a message with updated password and
        redirect to login page.
    """
    if current_user.is_authenticated:
        return redirect(url_for("papers.home"))
    user = User.verify_reset_token(token)
    if user is None:
        flash("That is an invalid or expired token", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode("utf-8")
        user.password = hashed_password
        db.session.commit()
        flash("Your password has been updated! You are now able to log in",
              "success")
        return redirect(url_for("users.login"))
    return render_template(
        "users/reset_token.html",
        title="Reset Password",
        form=form,
        js_files=["js/users/reset_password.js"],
    )


@users.route("/account/delete/")
@login_required
def delete_account():
    """To delete account of user
    """
    db.session.query(User).filter_by(id=current_user.id).delete(
        synchronize_session="fetch")
    db.session.commit()

flaskapp/templates/main/contact-us/contact_us_form.html
{% extends "headerFooter.html" %}

{% block general_top_links %}
 <a class="top_navigation_items" href={{ url_for("main.index") }}>
     <h4 class="py-2 mx-3">Home</h4>
 </a>
{% if image_file!="" %}
  <div class="dropdown_container">
     <h4 class="py-2 mx-3">More <i class="fa fa-caret-down"></i></h4>
     <div class="dropdown_items_container">
         <a class="top_navigation_items" href={{ url_for("main.about_us") }}>
             <h4 class="py-2 mx-3">About Us</h4>
         </a>
         <a class="top_navigation_items" href={{ url_for("main.help_page") }}>
             <h4 class="py-2 mx-3">Help</h4>
         </a>
         <a class="top_navigation_items" href={{ url_for("main.contact_us") }}>
             <h4 class="py-2 mx-3">Contact Us</h4>
         </a>
     </div>
 </div>

 <a class="top_navigation_items" href={{ url_for("users.logout") }}>
     <h4 class="py-2 mx-3">Log Out</h4>
 </a>
{% else %}
 <a class="top_navigation_items" href={{ url_for("main.about_us") }}>
     <h4 class="py-2 mx-3">About Us</h4>
 </a>
 <a class="top_navigation_items" href={{ url_for("main.help_page") }}>
     <h4 class="py-2 mx-3">Help</h4>
 </a>
 <a class="top_navigation_items" href={{ url_for("main.contact_us") }}>
     <h4 class="py-2 mx-3">Contact Us</h4>
 </a>
 <a class="top_navigation_items" href={{ url_for("users.login") }}>
     <h4 class="py-2 mx-3">Log In</h4>
 </a>

{% endif %}


{% endblock general_top_links %}

{% block general_side_links%}

  <a class="side_navigation_items" href={{ url_for("main.index") }}>Home</a>
  {% if image_file!="" %}
    <div class="dropdown_container_2 bb bt">
      <span class="side_navigation_items">More <i class="fa fa-caret-down"></i></span>
     
  </div>
  <a class="side_navigation_items" href={{ url_for("users.logout") }}>Log Out</a>
  {% else %}
 
  <a class="side_navigation_items" href={{ url_for("users.login") }}>
      Log In
  </a>
  {% endif %}

  <a href="#" class="side_navigation_items bb" id="close_link">Close</a>
{% endblock general_side_links %}

<div id="flash">
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %}
    <ul class="flashes">
        {% for category, message in messages %}
        <li class="{{ category }}">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %} {% endwith %}
</div>


{% block links %}
<link rel="stylesheet" crossorigin="anonymous"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.css" />
<link rel="stylesheet" crossorigin="anonymous"
    href="https://cdnjs.cloudflare.com/ajax/libs/hamburgers/1.1.3/hamburgers.min.css" />
<link rel="stylesheet" crossorigin="anonymous"
    href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" />
{% endblock links %}

{% block body %}


<div class="bg-contact100" style="background-image: url({{ url_for('static', filename='images/bg-01.jpg') }})">
    <div class="container-contact100">
        <div class="wrap-contact100">
            <div class="contact100-pic js-tilt" data-tilt>
                <img alt="IMG" src={{ url_for("static",
            filename="images/img-01.png") }}>
            </div>

            <form method="POST" action="" id="contactForm" class="contact100-form validate-form">
                {{ form.hidden_tag() }}
                <span class="contact100-form-title">
                    Get in touch
                </span>
                <div id="form_content">
                    <div class="wrap-input100 validate-input" data-validate="Name is required">
                        <label>
                            {{ form.name(class="input100", placeholder="Name") }} {#
                  <input
                    class="input100"
                    type="text"
                    name="name"
                    placeholder="Name"
                  />#}</label>
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-user" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
                        <label>{{ form.email(class="input100", placeholder="Email") }}</label>
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate="Valid mobile is required: 1234567890">
                        <label>{{ form.mobile(class="input100", placeholder="Mobile") }}</label>
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-mobile fa-1x" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate="Subject is required">
                        <label>{{ form.subject(class="input100", placeholder="Subject") }}</label>
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-indent" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate="Message is required">
                        <label>{{ form.message(class="input100", placeholder="Message") }}</label>
                        <span class="focus-input100"></span>
                    </div>

                    <div class="container-contact100-form-btn">
                        <button class="contact100-form-btn">
                            Send
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock body %}

{% block top_profile %}
{% if image_file!="" %}
 <div class="col4">
     <a class="profile_page" href={{ url_for("users.account") }}>
         <img src="{{ image_file }}" class="user" alt="{{loggedIn}}" title="profile" />
     </a>
 </div>
{% endif %}
{% endblock top_profile %}

{% block side_profile %}
 {% if image_file!="" %}
 <div class="col4">
     <a class="profile_page" href={{ url_for("users.account") }}>
         <img src="{{ image_file }}" class="user" alt="user" title="profile" />
     </a>
 </div>
{% endif %}
{% endblock side_profile %}




{% block script %}
<script>
    (function ($) {
        "use strict";


        var input = $(".validate-input .input100");

        $(".validate-form").on("submit", function () {
            var check = true;

            for (var i = 0; i < input.length; i++) {
                if (validate(input[i]) == false) {
                    showValidate(input[i]);
                    check = false;
                }
            }

            return check;
        });

        $(".validate-form .input100").each(function () {
            $(this).focus(function () {
                hideValidate(this);
            });
        });

        function validate(input) {
            if (
                $(input).attr("type") == "email" ||
                $(input).attr("name") == "email"
            ) {
                if (
                    $(input)
                    .val()
                    .trim()
                    .match(
                        /^([a-zA-Z0-9_\-.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9-]+\.)+))([a-zA-Z]{1,5}|[0-9]{1,3})(\]?)$/
                    ) == null
                ) {
                    return false;
                }
            } else {
                if ($(input).val().trim() == "") {
                    return false;
                }
            }
        }

        function showValidate(input) {
            var thisAlert = $(input).parent();

            $(thisAlert).addClass("alert-validate");
        }

        function hideValidate(input) {
            var thisAlert = $(input).parent();

            $(thisAlert).removeClass("alert-validate");
        }
    })(jQuery);
</script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/js/select2.min.js" type="text/javascript">
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/tilt.js/1.2.1/tilt.jquery.min.js" type="text/javascript">
</script>
<script>
    $(".js-tilt").tilt({
        scale: 1.1,
    });
</script>


<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag("js", new Date());

    gtag("config", "UA-23581568-13");
</script>
{% endblock script %}